apiVersion: v1
kind: ConfigMap
metadata:
  name: load-php
  namespace: {{ .Release.namespace}}
data:
  index.php: 'test'
  load.php: '<?php   $x = 0.0001;   for ($i = 0; $i <= 1000000; $i++) {     $x += sqrt($x);   }   echo "OK!"; ?>'
  phpinfo.php: '<?php phpinfo(); ?>'
