apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name}}
  namespace: {{ .Release.namespace}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name}}
  minReplicas: {{.Values.minReplicas}}
  maxReplicas: {{.Values.maxReplicas}}
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: server
      target:
        type: Utilization
        averageUtilization: {{.Values.targetCPUUtilizationPercentage}}

