apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 500
globalDefault: false
description: "Setter workload til lav prioritet for å tillate andre workloads når clusteret overbelastes"
