apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name}}-rolebinding
  namespace: {{ .Release.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name}}-role
subjects:
- kind: ServiceAccount
  name: default
- kind: ServiceAccount
  name: {{ .Release.Name}}-serviceaccount
  namespace: {{ .Release.namespace}}
