apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}
  namespace: {{ .Release.namespace}}
  labels:
    run: {{ .Release.Name}}
spec:
  ports:
  - port: 80
  selector:
    run: {{ .Release.Name}}
  type: NodePort
