apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinite-calls
  namespace: test1
  labels:
    app: infinite-calls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infinite-calls
  template:
    metadata:
      name: infinite-calls
      labels:
        app: infinite-calls
    spec:
      containers:
      - name: infinite-calls
        image: busybox
        command:
        - /bin/sh
        - -c
        - "while true; do sleep 0.01; wget -q -O- http://php-apache/load.php;  done"
